"""Render candidate facts using the user's supplied editorial portfolio design."""
from html import escape as esc
from pathlib import Path


def render(data, projects, family_label='职业经历与项目实践'):
    css = (Path(__file__).parents[1] / 'assets/portfolio-editorial.css').read_text()
    person = data['person']
    def bullets(entry):
        return '<ul>' + ''.join('<li>' + esc(b['zh']) + '</li>' for b in entry['bullets']) + '</ul>'
    cards = []
    for index, project in enumerate(projects):
        name, _, description = project['title_zh'].partition('｜')
        tags = list(dict.fromkeys(k for b in project['bullets'] for k in b.get('keywords', []) if any('\u4e00' <= c <= '\u9fff' for c in k)))[:4]
        cards.append('<article class="project-row"><div class="project-copy"><div class="project-meta"><span>0' + str(index + 1) + '</span><span>个人项目 · AI 辅助开发</span></div><h3>' + esc(name) + '</h3><h4>' + esc(description) + '</h4><p>' + esc(project['employment_zh'] + ' · ' + project['dates']) + '</p><ul class="tag-list">' + ''.join('<li>' + esc(t) + '</li>' for t in tags) + '</ul><p>真实用户反馈与个人贡献边界，保留复核。</p></div><div class="project-visual ' + ['pink', 'yellow', 'blue'][index % 3] + '"><div class="visual-toolbar"><span>PROJECT EVIDENCE</span><span>事实摘要 / 非产品截图</span></div><div class="evidence-copy">' + bullets(project) + '<p class="source">来源：' + esc(project['source_ref']) + '</p></div></div></article>')
    works = ''.join('<article class="experience"><h3>' + esc(e['title_zh']) + '</h3><p>' + esc(e['dates'] + ' · ' + e['employment_zh']) + '</p>' + bullets(e) + '</article>' for e in data['entries'] if e['kind'] == 'work')
    return '<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>' + esc(person['name_zh']) + ' · 个人作品集审阅稿</title><style>' + css + '\n.evidence-copy{padding:40px 12px;font-size:16px;line-height:1.9}.evidence-copy li{margin:20px 0}.source{font-size:11px;overflow-wrap:anywhere}.experience{padding:24px 0;border-top:1px solid;line-height:1.9}.draft-note{padding:12px 20px;text-align:center;background:#f4d958;font-size:12px}.hero{min-height:580px}ul{padding-left:22px}</style></head><body><div class="draft-note">本地审阅稿 · 依据简历事实生成 · 尚未发布 · 联系方式默认隐藏</div><header class="site-header"><a class="wordmark" href="#">' + esc(person['name_zh']) + ' <span>/ PORTFOLIO</span></a><nav><a href="#work">项目</a><a href="#experience">经历</a><a href="#about">关于</a></nav></header><main><section class="hero shell"><div class="eyebrow">' + esc(family_label) + '</div><h1>从真实经历，<br>到<em>可展示</em>的实践。</h1><div class="hero-bottom"><p>我是' + esc(person['name_zh']) + '。这里整理我的职业经历、项目交付与验证思考。</p><a class="text-link" href="#work">查看项目 ↓</a></div></section><section class="proof-strip"><div><strong>' + str(len(projects)) + '</strong><span>本次精选项目</span></div><div><strong>' + str(sum(e['kind'] == 'work' for e in data['entries'])) + '</strong><span>职业经历</span></div><div><strong>' + str(sum(len(p['bullets']) for p in projects)) + '</strong><span>项目事实条目</span></div><div><strong>证据</strong><span>贡献、交付与边界</span></div></section><section class="work shell" id="work"><header class="section-heading"><p>SELECTED WORK</p><h2>从项目中，认识我的实践。</h2></header>' + ''.join(cards) + '</section><section class="shell" id="experience"><header class="section-heading"><p>EXPERIENCE</p><h2>把一线经历，转化为可迁移的能力。</h2></header>' + works + '</section><section class="about shell" id="about"><div><p class="section-kicker">ABOUT</p><h2>' + esc(person['name_zh']) + '</h2></div><div class="about-copy"><p>' + esc(person.get('education_zh', '')) + '</p><p>' + esc(person.get('languages_zh', '')) + '</p><p>' + esc(person.get('location_zh', '')) + '</p></div></section><section class="contact"><div class="shell contact-inner"><p>LET’S BUILD SOMETHING USEFUL.</p><h2>让每一段经历，<br>都有清晰的表达。</h2><p>联系方式在发布前选择；本页不包含电话和邮箱。</p></div></section></main></body></html>'
